language: android

android:
   components:
   - tools
   - platform-tools
   - tools # Upgrade again after upgrading platform-tools.

jdk: oraclejdk8

sudo: required

before_install:
  # Skip build if the commit message contains [skip travis] or [travis skip]
   - >
       echo "$TRAVIS_COMMIT_MESSAGE"
       | grep -E  '\[(skip travis|travis skip)\]'
       && echo "[skip travis] has been found, exiting."
       && exit 0 || true
  
before_script:
  - chmod +x gradlew
  - mkdir -p $ANDROID_HOME/licenses
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - ./gradlew clean assembleDebug --no-daemon --stacktrace
  - fossa init
  # - fossa analyze

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

notifications:
  email: false
