language: android
jdk: oraclejdk8
sudo: false

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

licenses:
  - android-sdk-license-.+
  - '.+'

script: ./gradlew dependencies || true && ./gradlew clean assembleDebug

android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-27
    - extra-android-m2repository
    
