language: android
jdk: oraclejdk8
sudo: false

branches:
  only:
    - master

before_install:
  - chmod +x gradlew
  - mkdir -p "$ANDROID_SDK/licenses"
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_SDK/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_SDK/licenses/android-sdk-preview-license"
  
licenses:
  - android-sdk-license-.+
  - '.+'

script: ./gradlew dependencies || true && ./gradlew clean assembleDebug

android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-27
    - extra-android-m2repository
