# In case of problems see RxAndroid's script (https://github.com/ReactiveX/RxAndroid/blob/2.x/.travis.yml)

language: android

android:
  components:
    - tools
    - platform-tools

jdk: 
  - oraclejdk8

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"
  
before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
  - chmod +x gradlew

script:
  - ./gradlew clean assembleDebug --no-daemon --stacktrace
  - fossa init
  # - fossa analyze

# cache between builds
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

notifications:
  email: false
