language: android
jdk: oraclejdk8
sudo: false

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

script: ./gradlew dependencies || true && ./gradlew clean assembleDebug

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-25
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
