language: android
jdk: oraclejdk8
sudo: false

branches:
  only:
    - master

script: ./gradlew clean assembleDebug

android:
  components:
      - platform-tools
      - tools
      - build-tools-24.0.3
      - android-22
      - android-24
      - sys-img-armeabi-v7a-android-22
      - extra-android-m2repository
